# -Unhandled-Exception-error-mcedit-2.0.0beta14
MCEdit version: 2.0.0-beta14 Python version: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)] Platform: win32 System version: Windows-10-10.0.18362 Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel  Obtained a GL context with this format: Valid: True Version: 4.0 Hardware Accelerated: True Depth buffer: True, 24 Double buffer: True Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile  Driver info: GL_VERSION: 4.0.0 - Build 10.18.10.4358 (4, 0) GL_VENDOR: 'Intel' GL_RENDERER: 'Intel(R) HD Graphics 4000'  ------  Unhandled Exception  Traceback (most recent call last):   File "mcedit2\editorsession.py", line 1643, in viewOffsetChanged (self is a EditorTab)   File "mcedit2\worldview\minimap.py", line 187, in currentViewMatrixChanged (self is a MinimapWorldView)   File "mcedit2\util\raycast.py", line 30, in rayCastInBounds     File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)   File "mcedit2\util\raycast.py", line 77, in rayCast     File "mcedit2\util\raycast.py", line 215, in advanceToChunk     File "mceditlib\worldeditor.py", line 831, in getChunk (self is a WorldEditorDimension)   File "mceditlib\worldeditor.py", line 499, in getChunk (self is a WorldEditor)   File "mceditlib\cachefunc.py", line 77, in __call__     File "mceditlib\worldeditor.py", line 477, in _getChunkDataRaw (self is a WorldEditor)   File "mceditlib\anvil\adapter.py", line 922, in readChunk (self is a AnvilWorldAdapter) AnvilChunkFormatError: [Errno Error loading chunk: KeyError('Key Blocks not found.',)] None: &lt;traceback object at 0x000001F12CFB4188>  I don't know what to do! Somebody help me!
